const experienciasDisponibles = [
{   id: 1, 
    nombre: "Experiencia Malbec",
    uva: "Malbec",
    precio: 4500,
    vinos: ["Cordero con piel de lobo","El joven equilibrista","Animal - Orgánico","Pardillos", "Sapo de otro pozo","Il Forte"],
    img: "../media/wine.png",
},
{   id: 2, 
    nombre: "Experiencia Cabernet Sauvignion",
    uva: "Malbec",
    precio: 5500,
    vinos: ["Cordero con piel de lobo","El joven equilibrista","Animal - Orgánico","Pardillos", "Sapo de otro pozo","Il Forte"],
    img: "../media/wine.png",
},
{   id: 3, 
    nombre: "Experiencia Cabernet franc",
    uva: "Malbec",
    precio: 6500,
    vinos: ["Cordero con piel de lobo","El joven equilibrista","Animal - Orgánico","Pardillos", "Sapo de otro pozo","Il Forte"],
    img: "../media/wine.png",
},
]